#!/bin/bash
# Aion
#
# Ref: 
# * http://www.aionsource.com/topic/45256-aion-ports/

CHAIN='game-aion'

# clear chain
iptables -F $CHAIN
iptables -X $CHAIN

# create chain
iptables -N $CHAIN

iptables -A $CHAIN -p tcp --dport 2106 -j ACCEPT
iptables -A $CHAIN -p tcp --dport 2009 -j ACCEPT
iptables -A $CHAIN -p tcp --dport 7777 -j ACCEPT
iptables -A $CHAIN -p tcp --dport 10241 -j ACCEPT

iptables -A FORWARD -j $CHAIN
