#!/bin/bash

# iptable rules for game:
# Heroes of Newerth

CHAIN='game-newerth'

# clear chain
iptables -F $CHAIN
iptables -X $CHAIN

# create chain
iptables -N $CHAIN

iptables -A $CHAIN -p tcp --dport 11031 -j ACCEPT
iptables -A $CHAIN -p tcp --dport 11235:11335 -j ACCEPT
iptables -A $CHAIN -p udp --dport 11235:11335 -j ACCEPT

iptables -A FORWARD -j $CHAIN
