#!/bin/bash

CHAIN='game-gerena'

# clear chain
iptables -F $CHAIN
iptables -X $CHAIN

# create chain
iptables -N $CHAIN


iptables -A $CHAIN -p tcp --dport 7456 -j ACCEPT
iptables -A $CHAIN -p udp --dport 1513 -j ACCEPT

iptables -A FORWARD -j $CHAIN
