#!/bin/bash

# iptable rules for game:
# League of Legends
#
# Ref:
# * http://kb.leagueoflegends.com/questions/27/Required+Network+Ports

CHAIN='game-lol'

# clear chain
iptables -F $CHAIN
iptables -X $CHAIN

# create chain
iptables -N $CHAIN

iptables -A $CHAIN -p tcp --dport 2099 -j ACCEPT
iptables -A $CHAIN -p tcp --dport 5222 -j ACCEPT
iptables -A $CHAIN -p tcp --dport 5223 -j ACCEPT
iptables -A $CHAIN -p tcp --dport 8393 -j ACCEPT
iptables -A $CHAIN -p udp --dport 5000:5200 -j ACCEPT
iptables -A $CHAIN -p udp --dport 5202 -j ACCEPT

iptables -A $CHAIN -d 95.172.69.0/24 -j ACCEPT
iptables -A $CHAIN -d 74.201.71.0/24 -j ACCEPT
iptables -A $CHAIN -d 66.151.54.0/24 -j ACCEPT

iptables -A FORWARD -j $CHAIN
