#!/bin/bash

# Teamspeak 3

CHAIN='teamspeak3'

# clear chain
iptables -F $CHAIN
iptables -X $CHAIN

# create chain
iptables -N $CHAIN


iptables -A $CHAIN -p tcp --dport 2008 -j ACCEPT
iptables -A $CHAIN -p tcp --dport 30033 -j ACCEPT
iptables -A $CHAIN -p tcp --dport 10011 -j ACCEPT
iptables -A $CHAIN -p tcp --dport 9987:10237 -j ACCEPT
iptables -A $CHAIN -p udp --dport 30033 -j ACCEPT
iptables -A $CHAIN -p udp --dport 10011 -j ACCEPT
iptables -A $CHAIN -p udp --dport 9987:10237 -j ACCEPT

iptables -A FORWARD -j $CHAIN
