#!/bin/bash

# iptable rules for game:
# Poker Stars
#

CHAIN='game-pokerstars'

# clear chain
iptables -F $CHAIN
iptables -X $CHAIN

# create chain
iptables -N $CHAIN

iptables -A $CHAIN -p tcp --dport 26002 -j ACCEPT

iptables -A FORWARD -j $CHAIN
