#!/bin/bash

# Monday Night Conflict
# * http://forums.steampowered.com/forums/showthread.php?t=1654598

CHAIN='game-steam-mondaynightconflict'

# clear chain
iptables -F $CHAIN
iptables -X $CHAIN

# create chain
iptables -N $CHAIN

iptables -A $CHAIN -p udp --dport 7777:7778 -j ACCEPT
iptables -A FORWARD -j $CHAIN
