#!/bin/bash
# Cabal
#
# Refs:
# * http://forum.cabalonline.com/showthread.php?7123-SOLUTION-Configuring-your-firewall
# * http://forum.cabalonline.com/showthread.php?t=7123
#
# TCP 38111-38125
# UDP ports 6800-6899 ==> Bittorent is default 6881-6889 TCP so should be okay ?
# 

CHAIN='game-cabal'

# clear chain
iptables -F $CHAIN
iptables -X $CHAIN

# create chain
iptables -N $CHAIN

iptables -A $CHAIN -p tcp --dport 38111:38125 -j ACCEPT
iptables -A $CHAIN -p udp --dport 6800:6899 -j ACCEPT

iptables -A FORWARD -j $CHAIN
