#!/bin/bash

# iptable rules for game:
# PWI - Perfect World

CHAIN='game-pwi'

# clear chain
iptables -F $CHAIN
iptables -X $CHAIN

# create chain
iptables -N $CHAIN

iptables -A $CHAIN -p tcp --dport 29000 -j ACCEPT
iptables -A $CHAIN -p udp --dport 29000 -j ACCEPT

iptables -A FORWARD -j $CHAIN
