#!/bin/bash

# FoM Streaming

IP_STREAMING=172.16.1.252
MARK=5

# Redirect traffic over line $MARK
iptables -t mangle -A PREROUTING --source $IP_STREAMING -j MARK --set-mark $MARK

# Allow traffic to pass through
iptables -t filter -A FORWARD --source $IP_STREAMING -j ACCEPT 

IP_STREAMING=172.16.5.253
MARK=5

# Redirect traffic over line $MARK
iptables -t mangle -A PREROUTING --source $IP_STREAMING -j MARK --set-mark $MARK

# Allow traffic to pass through
iptables -t filter -A FORWARD --source $IP_STREAMING -j ACCEPT 

IP_STREAMING=172.16.34.1
MARK=5

# Redirect traffic over line $MARK
iptables -t mangle -A PREROUTING --source $IP_STREAMING -j MARK --set-mark $MARK

# Allow traffic to pass through
iptables -t filter -A FORWARD --source $IP_STREAMING -j ACCEPT 
